name: AWS Job with Vault

on:
  push:
    branches:
      - main

jobs:
  aws_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vault CLI
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt update && sudo apt install -y vault    

      - name: Authenticate to Vault
        run: |
          export VAULT_ADDR="http://47.128.235.138:8200/"
          export VAULT_TOKEN="${{ secrets.VAULT_TOKEN }}"
          vault login $VAULT_TOKEN
          echo "VAULT_ADDR is: $VAULT_ADDR"

      # - name: Retrieve AWS Credentials from Vault
      #   run: |
      #     export VAULT_ADDR="http://47.128.235.138:8200/"
      #     export VAULT_TOKEN="${{ secrets.VAULT_TOKEN }}"
          
      #     # Debug: Check Vault connection
      #     curl -v $VAULT_ADDR/v1/sys/health
          
      #     # Read AWS credentials explicitly using VAULT_ADDR
      #     AWS_CREDS=$(vault read -format=json aws/creds/root)
          
      #     echo "AWS_ACCESS_KEY_ID=$(echo $AWS_CREDS | jq -r '.data.access_key')" >> $GITHUB_ENV
      #     echo "AWS_SECRET_ACCESS_KEY=$(echo $AWS_CREDS | jq -r '.data.secret_key')" >> $GITHUB_ENV
      #   env:
      #     VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      #     VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

      #     - name: Read AWS credentials from Vault
      - name: Read AWS credentials from Vault
        run: |
          echo "Retrieving AWS credentials..."
          AWS_CREDS=$(vault read -format=json aws/creds/root)
          echo "RAW AWS_CREDS: ${AWS_CREDS:0:100}..."  # Print first 100 chars for debugging
          ACCESS_KEY=$(echo $AWS_CREDS | jq -r '.data.access_key')
          SECRET_KEY=$(echo $AWS_CREDS | jq -r '.data.secret_key')
          
          echo "Extracted AWS_ACCESS_KEY_ID: ${ACCESS_KEY:0:4}********"
          echo "Extracted AWS_SECRET_ACCESS_KEY: ********${SECRET_KEY: -4}"
          
          echo "AWS_ACCESS_KEY_ID=$ACCESS_KEY" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$SECRET_KEY" >> $GITHUB_ENV
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region ap-southeast-1
          
      - name: Verify AWS Credentials
        run: aws sts get-caller-identity   

      # - name: Run AWS Job
      #   run: |
      #     aws s3 ls  # Example AWS job
